Resolve numpy.reshape() error
TypeError: 'float' object cannot be interpreted as an integer when using numpy.reshape(). By using the floor instead of division, this issue was resolved: https://stackoverflow.com/questions/42989289/python-typeerror-float-object-cannot-be-interpreted-as-an-integer